### ISSUE TITLE
Check if all required plugins are installed

### ISSUE THREAD

**Issue by addun** [cdgstudio/website#6]
Add a action to check if all required plugins are installed.

Required plugins are:
- [ACF Plugin](https://www.advancedcustomfields.com/)

**Comment by Adibzadeh** [comment]
I would like to do this task, assign it to me if it's okay.

**Comment by addun** [comment]
If you have any questions do not mind to ask.

**Comment by Adibzadeh** [comment]
I made a pr for this #8
